module.exports = {
	getSkills () {
		return skills = [
			{
				"Name": "Acrobatie",
				"Description": "Esquive et se déplace plus facilement",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Adrénaline",
				"Description": "Rester sous adrénaline jusqu’à la fin du combat",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Alchimie",
				"Description": "Créer et connaître les effets des potions",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Alcool (résistance)",
				"Description": "Addiction et résistance à l'alcool",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Ambidextre",
				"Description": "Utiliser 1 arme par main",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Animaux",
				"Description": "Connaissance et Compréhension des animaux",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Artisanat",
				"Description": "Réparer et Fabriquer des objets simples",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Botte secrète",
				"Description": "Effectue une attaque inconnue qui marche à tous les coups",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Bourrin",
				"Description": "Détruire tous types d'objets avec assez de force",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 10,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Cartographe",
				"Description": "Dessiner et Lire des cartes",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Charisme",
				"Description": "Séduire les gens du sexe opposé pour être “obéi”",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Concentration",
				"Description": "Il est plus facile de se concentrer",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Cuisine",
				"Description": "Pour ne pas mourir de faim lors des longs trajets",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Dissimulation",
				"Description": "Se cacher soi et des objets plus facilement",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Dressage",
				"Description": "Apaiser certaine créatures ou monstres pas trop agressifs",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Ecrire/ Lire",
				"Description": "Rend aussi intelligent qu'ne enfant en bas âge",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Eloquence",
				"Description": "Mieux parler pour convaincre plus facilement les autres",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Equitation",
				"Description": "Chevaucher sans problèmes tous types d’animaux sellés ou non",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Erudition",
				"Description": "Avoir fait des études de magie pour maîtriser plus de sorts",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Héraldique",
				"Description": "Être connu des dirigeants des villes où l'on a aidé",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Herboristerie",
				"Description": "Connaître les plantes et leur utilisation",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Insensible",
				"Description": "Immuniser contre la douleur et les effets en tout genre",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Intimidation",
				"Description": "Augmente la probabilité que les gens se rendent / “obéissent”",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 10,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Jeu d'argent",
				"Description": "Augmenter la probabilité de gagner aux jeux d'argent",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Langues",
				"Description": "Comprendre et déchiffrer des langues mortes et étrangères",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Larcins",
				"Description": "Faciliter pour commettre des petits crimes en tout genre",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Lecture Lèvre",
				"Description": "Entendre les conversations à distance",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Légendes",
				"Description": "Connaître les légendes et mythes des villages visité",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Médecine",
				"Description": "Permet de soigner certaines blessures pour économiser de la magie",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Métallurgie",
				"Description": "Connaissance des métaux et minéraux et leur utilité",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Natation",
				"Description": "Savoir nager en étant sûr de ne pas se noyer",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Navigation",
				"Description": "Connaissance maritime pour manoeuvrer une embarcation sur l’eau",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Piège",
				"Description": "Détection et Fabrication de pièges",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Poison (résistance)",
				"Description": "Création et résistance à certain poisons",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Sixième sens",
				"Description": "Prédire une situation dangereuse imminente",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Sommeil léger",
				"Description": "Rester sur ses gardes en dormant",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Stressé",
				"Description": "Permet de passer sous Adrénaline à n’importe quel moment",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 5,
				"2 Hands/ Heavy": 5,
				"Shield/ Protection": 10,
				"Bow/ Range": 5,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Théologie",
				"Description": "Connaissance sur les religions et les cultes",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Veinard",
				"Description": "Une fois par session, tromper le destin et changer un échec critique en réussite",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Vue perçante",
				"Description": "Détecter les ennemis de plus loin",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 10,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
		];
	}
}
/*
			{
				"Name": "",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
*/