module.exports = {
	getSkills () {
		return skills = [
			{
				"Name": "Acrobatie",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Adrénaline",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Alchimie",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Alcool (résistance)",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Ambidextre",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Animaux",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Artisanat",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Botte secrète",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Bourrin",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 10,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Cartographe",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Charisme",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Concentration",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Cuisine",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Dissimulation",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Dressage",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Ecrire/ Lire",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Eloquence",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Equitation",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Erudition",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Héraldique",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Herboristerie",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Insensible",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Intimidation",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 10,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Jeu d'argent",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Langues",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Larcins",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Lecture Lèvre",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Légendes",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Médecine",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Métallurgie",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Natation",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Navigation",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Piège",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Piège",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Poison (résistance)",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Réactif",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 5,
				"2 Hands/ Heavy": 5,
				"Shield/ Protection": 10,
				"Bow/ Range": 5,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Sommeil léger",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Sicième sens",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Théologie",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Veinard",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Vue perçante",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 10,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
		];
	}
}
/*
			{
				"Name": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
*/