module.exports = {
	getSkills () {
		return skills = [
			{
				"Name": "Acrobatie",
				"Description": "",
				"Description": "",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Adrénaline",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Alchimie",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Alcool (résistance)",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Ambidextre",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Animaux",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Artisanat",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Botte secrète",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Bourrin",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 10,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Cartographe",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Charisme",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Concentration",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Cuisine",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Dissimulation",
				"Description": "",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Dressage",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Ecrire/ Lire",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Eloquence",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Equitation",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Erudition",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Héraldique",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Herboristerie",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Insensible",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Intimidation",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 10,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Jeu d'argent",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Langues",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Larcins",
				"Description": "",
				
				"Agility": 10,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Lecture Lèvre",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Légendes",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Médecine",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Métallurgie",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Natation",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Navigation",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Piège",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Piège",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Poison (résistance)",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Réactif",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 5,
				"2 Hands/ Heavy": 5,
				"Shield/ Protection": 10,
				"Bow/ Range": 5,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Sommeil léger",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Sicième sens",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Théologie",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Veinard",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
			{
				"Name": "Vue perçante",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 20,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 10,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
		];
	}
}
/*
			{
				"Name": "",
				"Description": "",
				
				"Agility": 0,
				"Strength": 0,
				"Perception": 0,
				"Mental": 0,
				
				"1 Hand/ Light": 0,
				"2 Hands/ Heavy": 0,
				"Shield/ Protection": 0,
				"Bow/ Range": 0,
				
				"Water": 0,
				"Earth": 0,
				"Air": 0,
				"Lightning": 0,
				"Darkness": 0,
				"Light": 0,
				"Fire": 0,
				
				"HP": 0,
				"MP": 0,
				"Dmg": 0,
				"Armor": 0,
			},
*/